### PR TITLE
Fix for updates to pycountry and netaddr

### PR DESCRIPTION
**Pull request by vangesseld**
### pycountry updates

Updated calls to pycountry.countries.get to use alpha_2 instead of alpha2 argument. 
Updated error checking logic due to newer versions of pycountry returning None for failed lookups. 

### netaddr updates

Updated test case for reserved network. Netaddr no longer recognizes 192.0.0.0/24 as reserved space, updated test case to use 192.0.2.0/24 (TEST-NET) which is recognized as reserved space.

### CODE REVIEW

**Comment by rwielk** [comment]
Hi @vangesseld ,

I'd be ready to merge your PR.
Could you please solve the merge conflict ?
Just use your requirements, I had to tight it to get CI working without introducing your fixes.
When it runs through CI I'll merge it and build the release.
Thanks.

Br
Raiko

**Comment by rwielk** [comment]
Hi @vangesseld,

thanks and allright, approved you now.
It seems we did not notice a logical change the PR introduces, see the test results, which have to be fixed before this one could be merged.
Do you want to do some investigations ?
If not I will, but I'm not sure when I'll find the time.
I think one has to look into how this changes the validation results.

BR
Raiko

**Comment by vangesseld** [comment]
Hi @rwielk, 

I think this has been resolved and tests are now passing in my environment. 

It seems that due to the changes in the pycountry .get methods in more recent versions, both blank strings and invalid strings return a None value. I have fixed the logic by updating the _check_errors methods on the Country and Subdivision fields to check for a blank string prior to querying pycountry. 

Looks like you need to approve the CI/CD run again, but I think it should pass this time. 

Thank you!

**Comment by rwielk** [comment]
HI @vangesseld ,

got it, nice catch.
I'll try to merge this and build a new release on monday.
Tank you!

Regards,
Raiko

**Pull request merged**
